source 'http://rubygems.org'

gem 'rails', '3.1.0'
#code below was pasted in
# use Haml for templates
gem 'haml'
# use Ruby debugger
#group :development, :test do
#  gem 'ruby-debug19'
#end
#
# for Heroku, replace "gem 'sqlite3'" in your Gemfile with this:
group :development, :test do
  gem 'ruby-debug19'
  # if you already have a 'group :development,:test' block in your
  # Gemfile, you can just move the line "gem 'sqlite3'" into it.
  gem 'sqlite3' # use SQLite only in development and testing
end 
group :production do
  gem 'pg' # use PostgreSQL in production (Heroku)
end
# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
  gem 'therubyracer'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
# add to end of Gemfile---section 5.4
# The ruby tmdb-gem
gem 'ruby-tmdb'

group :test, :development do
  gem 'cucumber-rails', :require => false
  gem 'cucumber-rails-training-wheels' # some pre-fabbed step definitions  
  gem 'database_cleaner' # to clear Cucumber's test database between runs
  gem 'capybara'         # lets Cucumber pretend to be a web browser
  gem 'launchy'          # a useful debugging aid for user stories
  gem 'rspec-rails'
  gem 'ZenTest'
end

